-- ============================================
-- RPC Function: get_travel_authority_region_counts
-- ============================================
-- Derive a region grouping from the free-text destination field so the dashboard
-- does not need to classify every destination row in browser JavaScript.
--
-- This keeps region data as a derived value instead of requiring users to fill a
-- mandatory region field in every travel authority entry.
--
-- Pattern used here:
-- - maintain a small alias table instead of a giant CASE expression
-- - use priority to resolve overlapping names like "San Jose" that appear in
--   multiple regions
-- - keep destination as the source of truth and infer region dynamically

DROP FUNCTION IF EXISTS public.get_travel_authority_region_counts();
DROP TABLE IF EXISTS public.destination_region_aliases;

CREATE TABLE IF NOT EXISTS public.destination_region_aliases (
    alias TEXT PRIMARY KEY,
    region TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 100
);

INSERT INTO public.destination_region_aliases (alias, region, priority)
WITH dedup AS (
    SELECT
        alias,
        region,
        priority,
        ROW_NUMBER() OVER (
            PARTITION BY alias
            ORDER BY priority DESC, region ASC
        ) AS rn
    FROM (
        VALUES
            ('quezon city', 'NCR', 1000),
            ('makati city', 'NCR', 1000),
            ('taguig city', 'NCR', 1000),
            ('pasay city', 'NCR', 1000),
            ('marikina city', 'NCR', 1000),
            ('mandaluyong city', 'NCR', 1000),
            ('manila city', 'NCR', 1000),
            ('metro manila', 'NCR', 800),
            ('national capital', 'NCR', 800),
            ('manila', 'NCR', 700),
            ('pasig', 'NCR', 700),
            ('taguig', 'NCR', 700),
            ('makati', 'NCR', 700),
            ('paranaque', 'NCR', 700),
            ('valenzuela', 'NCR', 700),
            ('caloocan', 'NCR', 700),
            ('las pinas', 'NCR', 700),
            ('muntinlupa', 'NCR', 700),
            ('navotas', 'NCR', 700),
            ('malabon', 'NCR', 700),
            ('baguio', 'CAR', 1000),
            ('benguet', 'CAR', 900),
            ('ifugao', 'CAR', 900),
            ('kalinga', 'CAR', 900),
            ('apayao', 'CAR', 900),
            ('abra', 'CAR', 900),
            ('mountain province', 'CAR', 900),
            ('tabuk', 'CAR', 900),
            ('la trinidad', 'CAR', 900),
            ('bangued', 'CAR', 900),
            ('sagada', 'CAR', 900),
            ('ilocos norte', 'Region I', 900),
            ('ilocos sur', 'Region I', 900),
            ('la union', 'Region I', 900),
            ('pangasinan', 'Region I', 900),
            ('vigan', 'Region I', 900),
            ('laoag', 'Region I', 900),
            ('dagupan', 'Region I', 900),
            ('urdaneta', 'Region I', 900),
            ('lingayen', 'Region I', 900),
            ('alaminos', 'Region I', 900),
            ('tuguegarao', 'Region II', 1000),
            ('bayombong', 'Region II', 1000),
            ('isabela', 'Region II', 900),
            ('nueva vizcaya', 'Region II', 900),
            ('quirino', 'Region II', 900),
            ('cagayan', 'Region II', 900),
            ('santiago city', 'Region II', 1000),
            ('ilagan', 'Region II', 900),
            ('cauayan', 'Region II', 900),
            ('cabagan', 'Region II', 900),
            ('clark', 'Region III', 1000),
            ('subic', 'Region III', 1000),
            ('angeles', 'Region III', 1000),
            ('tarlac city', 'Region III', 1000),
            ('cabanatuan city', 'Region III', 1000),
            ('o longapo city', 'Region III', 1000),
            ('san jose del monte city', 'Region III', 1000),
            ('san jose del monte', 'Region III', 1000),
            ('balanga', 'Region III', 900),
            ('dinalupihan', 'Region III', 900),
            ('orani', 'Region III', 900),
            ('palayan', 'Region III', 900),
            ('gapan', 'Region III', 900),
            ('bulacan', 'Region III', 800),
            ('pampanga', 'Region III', 800),
            ('tarlac', 'Region III', 800),
            ('nueva ecija', 'Region III', 800),
            ('zambales', 'Region III', 800),
            ('bataan', 'Region III', 800),
            ('malolos', 'Region III', 800),
            ('cabanatuan', 'Region III', 800),
            ('olongapo', 'Region III', 800),
            ('tagaytay city', 'CALABARZON', 1000),
            ('general trias city', 'CALABARZON', 1000),
            ('trece martires city', 'CALABARZON', 1000),
            ('bacoor city', 'CALABARZON', 1000),
            ('calamba city', 'CALABARZON', 1000),
            ('santa rosa city', 'CALABARZON', 1000),
            ('biñan city', 'CALABARZON', 1000),
            ('binan city', 'CALABARZON', 1000),
            ('cabuyao city', 'CALABARZON', 1000),
            ('san pablo city', 'CALABARZON', 1000),
            ('lipa city', 'CALABARZON', 1000),
            ('tanauan city', 'CALABARZON', 1000),
            ('antipolo city', 'CALABARZON', 1000),
            ('lucena city', 'CALABARZON', 1000),
            ('cavite', 'CALABARZON', 900),
            ('bacoor', 'CALABARZON', 900),
            ('dasmarinas', 'CALABARZON', 900),
            ('imus', 'CALABARZON', 900),
            ('laguna', 'CALABARZON', 900),
            ('calamba', 'CALABARZON', 900),
            ('santa rosa', 'CALABARZON', 900),
            ('binan', 'CALABARZON', 900),
            ('san pedro', 'CALABARZON', 900),
            ('cabuyao', 'CALABARZON', 900),
            ('batangas', 'CALABARZON', 900),
            ('lipa', 'CALABARZON', 900),
            ('tanauan', 'CALABARZON', 900),
            ('nasugbu', 'CALABARZON', 900),
            ('antipolo', 'CALABARZON', 900),
            ('cainta', 'CALABARZON', 900),
            ('taytay', 'CALABARZON', 900),
            ('angono', 'CALABARZON', 900),
            ('binangonan', 'CALABARZON', 900),
            ('lucena', 'CALABARZON', 900),
            ('quezon province', 'CALABARZON', 900),
            ('sariaya', 'CALABARZON', 900),
            ('gumaca', 'CALABARZON', 900),
            ('infanta', 'CALABARZON', 900),
            ('puerto princesa city', 'MIMAROPA', 1000),
            ('san jose occidental mindoro', 'MIMAROPA', 1000),
            ('palawan', 'MIMAROPA', 900),
            ('mindoro', 'MIMAROPA', 900),
            ('romblon', 'MIMAROPA', 900),
            ('marinduque', 'MIMAROPA', 900),
            ('puerto princesa', 'MIMAROPA', 900),
            ('coron', 'MIMAROPA', 900),
            ('el nido', 'MIMAROPA', 900),
            ('calapan', 'MIMAROPA', 900),
            ('boac', 'MIMAROPA', 900),
            ('odiongan', 'MIMAROPA', 900),
            ('legazpi city', 'Region V', 1000),
            ('naga city', 'Region V', 1000),
            ('sorsogon city', 'Region V', 1000),
            ('masbate city', 'Region V', 1000),
            ('san jose camarines sur', 'Region V', 1000),
            ('san jose cam sur', 'Region V', 1000),
            ('albay', 'Region V', 900),
            ('legazpi', 'Region V', 900),
            ('tabaco', 'Region V', 900),
            ('ligao', 'Region V', 900),
            ('daraga', 'Region V', 900),
            ('catanduanes', 'Region V', 900),
            ('masbate', 'Region V', 900),
            ('sorsogon', 'Region V', 900),
            ('naga', 'Region V', 900),
            ('bicol', 'Region V', 900),
            ('virac', 'Region V', 900),
            ('daet', 'Region V', 900),
            ('caramoan', 'Region V', 900),
            ('gubat', 'Region V', 900),
            ('iloilo city', 'Region VI', 1000),
            ('bacolod', 'Region VI', 1000),
            ('kalibo city', 'Region VI', 1000),
            ('talisay city', 'Region VI', 1000),
            ('iloilo', 'Region VI', 900),
            ('capiz', 'Region VI', 900),
            ('aklan', 'Region VI', 900),
            ('antique', 'Region VI', 900),
            ('guimaras', 'Region VI', 900),
            ('negros occidental', 'Region VI', 900),
            ('kalibo', 'Region VI', 900),
            ('roxas city', 'Region VI', 900),
            ('dumangas', 'Region VI', 900),
            ('sagay', 'Region VI', 900),
            ('silay', 'Region VI', 900),
            ('bago', 'Region VI', 900),
            ('kabankalan', 'Region VI', 900),
            ('cebu city', 'Region VII', 1000),
            ('mandaue city', 'Region VII', 1000),
            ('lapu lapu city', 'Region VII', 1000),
            ('tagbilaran city', 'Region VII', 1000),
            ('dumaguete city', 'Region VII', 1000),
            ('cebu', 'Region VII', 900),
            ('bohol', 'Region VII', 900),
            ('negros oriental', 'Region VII', 900),
            ('siquijor', 'Region VII', 900),
            ('mandaue', 'Region VII', 900),
            ('lapu lapu', 'Region VII', 900),
            ('tagbilaran', 'Region VII', 900),
            ('dumaguete', 'Region VII', 900),
            ('talisay', 'Region VII', 900),
            ('toledo', 'Region VII', 900),
            ('bogo', 'Region VII', 900),
            ('bayawan', 'Region VII', 900),
            ('tacloban city', 'Region VIII', 1000),
            ('ormoc city', 'Region VIII', 1000),
            ('catbalogan city', 'Region VIII', 1000),
            ('maasin city', 'Region VIII', 1000),
            ('leyte', 'Region VIII', 900),
            ('samar', 'Region VIII', 900),
            ('biliran', 'Region VIII', 900),
            ('tacloban', 'Region VIII', 900),
            ('ormoc', 'Region VIII', 900),
            ('catbalogan', 'Region VIII', 900),
            ('maasin', 'Region VIII', 900),
            ('baybay', 'Region VIII', 900),
            ('zamboanga city', 'Region IX', 1000),
            ('dipolog', 'Region IX', 1000),
            ('pagadian', 'Region IX', 1000),
            ('isabela city', 'Region IX', 1000),
            ('zamboanga', 'Region IX', 900),
            ('dapitan', 'Region IX', 900),
            ('midsayap', 'Region IX', 900),
            ('sindangan', 'Region IX', 900),
            ('jose dalman', 'Region IX', 900),
            ('cagayan de oro', 'Region X', 1000),
            ('iligan', 'Region X', 1000),
            ('malaybalay', 'Region X', 1000),
            ('valencia', 'Region X', 1000),
            ('gingoog', 'Region X', 1000),
            ('misamis oriental', 'Region X', 900),
            ('misamis occidental', 'Region X', 900),
            ('bukidnon', 'Region X', 900),
            ('camiguin', 'Region X', 900),
            ('lanao del norte', 'Region X', 900),
            ('oroquieta', 'Region X', 900),
            ('ozamiz', 'Region X', 900),
            ('tangub', 'Region X', 900),
            ('davao city', 'Region XI', 1000),
            ('tagum city', 'Region XI', 1000),
            ('digos city', 'Region XI', 1000),
            ('mati city', 'Region XI', 1000),
            ('samal', 'Region XI', 1000),
            ('davao', 'Region XI', 900),
            ('tagum', 'Region XI', 900),
            ('digos', 'Region XI', 900),
            ('compostela valley', 'Region XI', 900),
            ('mati', 'Region XI', 900),
            ('panabo', 'Region XI', 900),
            ('baganga', 'Region XI', 900),
            ('general santos city', 'Region XII', 1000),
            ('koronadal city', 'Region XII', 1000),
            ('kidapawan city', 'Region XII', 1000),
            ('tacurong city', 'Region XII', 1000),
            ('cotabato city', 'Region XII', 1000),
            ('south cotabato', 'Region XII', 900),
            ('north cotabato', 'Region XII', 900),
            ('sultan kudarat', 'Region XII', 900),
            ('sarangani', 'Region XII', 900),
            ('general santos', 'Region XII', 900),
            ('koronadal', 'Region XII', 900),
            ('kidapawan', 'Region XII', 900),
            ('tacurong', 'Region XII', 900),
            ('cotabato', 'Region XII', 900),
            ('polomolok', 'Region XII', 900),
            ('glan', 'Region XII', 900),
            ('butuan city', 'Region XIII', 1000),
            ('surigao city', 'Region XIII', 1000),
            ('tandag city', 'Region XIII', 1000),
            ('bislig city', 'Region XIII', 1000),
            ('agusan del norte', 'Region XIII', 900),
            ('agusan del sur', 'Region XIII', 900),
            ('surigao del norte', 'Region XIII', 900),
            ('surigao del sur', 'Region XIII', 900),
            ('dinagat islands', 'Region XIII', 900),
            ('butuan', 'Region XIII', 900),
            ('caraga', 'Region XIII', 900),
            ('tandag', 'Region XIII', 900),
            ('bislig', 'Region XIII', 900),
            ('cabadbaran', 'Region XIII', 900),
            ('jolo city', 'BARMM', 1000),
            ('lamitan city', 'BARMM', 1000),
            ('marawi city', 'BARMM', 1000),
            ('bongao', 'BARMM', 1000),
            ('cotabato city', 'BARMM', 1000),
            ('maguindanao', 'BARMM', 900),
            ('lanao del sur', 'BARMM', 900),
            ('basilan', 'BARMM', 900),
            ('sulu', 'BARMM', 900),
            ('tawi tawi', 'BARMM', 900),
            ('marawi', 'BARMM', 900),
            ('bangsamoro', 'BARMM', 900),
            ('jolo', 'BARMM', 900),
            ('lamitan', 'BARMM', 900),
            ('parang', 'BARMM', 900),
            ('malabang', 'BARMM', 900),
            ('metro manila', 'NCR', 800),
            ('national capital', 'NCR', 800),
            ('quezon city', 'NCR', 800),
            ('makati', 'NCR', 800),
            ('pasig', 'NCR', 800),
            ('taguig', 'NCR', 800),
            ('marikina', 'NCR', 800),
            ('caloocan', 'NCR', 800),
            ('las pinas', 'NCR', 800),
            ('malabon', 'NCR', 800),
            ('mandaluyong', 'NCR', 800),
            ('muntinlupa', 'NCR', 800),
            ('navotas', 'NCR', 800),
            ('paranaque', 'NCR', 800),
            ('pasay', 'NCR', 800),
            ('pateros', 'NCR', 800),
            ('valenzuela', 'NCR', 800),
            ('manila', 'NCR', 800),
            ('baguio', 'CAR', 700),
            ('benguet', 'CAR', 700),
            ('ifugao', 'CAR', 700),
            ('kalinga', 'CAR', 700),
            ('apayao', 'CAR', 700),
            ('abra', 'CAR', 700),
            ('mountain province', 'CAR', 700),
            ('tabuk', 'CAR', 700),
            ('vigan', 'CAR', 700),
            ('laoag', 'CAR', 700),
            ('san fernando', 'CAR', 700),
            ('bulacan', 'Region III', 700),
            ('pampanga', 'Region III', 700),
            ('tarlac', 'Region III', 700),
            ('nueva ecija', 'Region III', 700),
            ('zambales', 'Region III', 700),
            ('bataan', 'Region III', 700),
            ('malolos', 'Region III', 700),
            ('cabanatuan', 'Region III', 700),
            ('clark', 'Region III', 700),
            ('olongapo', 'Region III', 700),
            ('subic', 'Region III', 700),
            ('angeles', 'Region III', 700),
            ('cavite', 'CALABARZON', 700),
            ('laguna', 'CALABARZON', 700),
            ('batangas', 'CALABARZON', 700),
            ('antipolo', 'CALABARZON', 700),
            ('calamba', 'CALABARZON', 700),
            ('santa rosa', 'CALABARZON', 700),
            ('binan', 'CALABARZON', 700),
            ('san pablo', 'CALABARZON', 700),
            ('cabuyao', 'CALABARZON', 700),
            ('lipa', 'CALABARZON', 700),
            ('lucena', 'CALABARZON', 700),
            ('quezon province', 'CALABARZON', 700),
            ('sariaya', 'CALABARZON', 700),
            ('tiaong', 'CALABARZON', 700),
            ('gumaca', 'CALABARZON', 700),
            ('infanta', 'CALABARZON', 700),
            ('ilocos norte', 'Region I', 700),
            ('ilocos sur', 'Region I', 700),
            ('la union', 'Region I', 700),
            ('pangasinan', 'Region I', 700),
            ('vigan', 'Region I', 700),
            ('laoag', 'Region I', 700),
            ('dagupan', 'Region I', 700),
            ('urdaneta', 'Region I', 700),
            ('lingayen', 'Region I', 700),
            ('alaminos', 'Region I', 700),
            ('butuan', 'Region XIII', 700),
            ('caraga', 'Region XIII', 700),
            ('tandag', 'Region XIII', 700),
            ('surigao', 'Region XIII', 700),
            ('davao', 'Region XI', 700),
            ('tagum', 'Region XI', 700),
            ('digos', 'Region XI', 700),
            ('mati', 'Region XI', 700),
            ('zamboanga', 'Region IX', 700),
            ('dipolog', 'Region IX', 700),
            ('pagadian', 'Region IX', 700),
            ('cebu', 'Region VII', 700),
            ('bohol', 'Region VII', 700),
            ('negros oriental', 'Region VII', 700),
            ('siquijor', 'Region VII', 700),
            ('leyte', 'Region VIII', 700),
            ('samar', 'Region VIII', 700),
            ('biliran', 'Region VIII', 700),
            ('tacloban', 'Region VIII', 700),
            ('ormoc', 'Region VIII', 700),
            ('catbalogan', 'Region VIII', 700),
            ('basilan', 'BARMM', 700),
            ('sulu', 'BARMM', 700),
            ('tawi tawi', 'BARMM', 700),
            ('marawi', 'BARMM', 700),
            ('jolo', 'BARMM', 700),
            ('lamitan', 'BARMM', 700),
            ('parang', 'BARMM', 700),
            ('malabang', 'BARMM', 700)
    ) AS v(alias, region, priority)
)
SELECT alias, region, priority
FROM dedup
WHERE rn = 1
ON CONFLICT (alias) DO UPDATE
SET region = EXCLUDED.region,
    priority = EXCLUDED.priority;

CREATE OR REPLACE FUNCTION public.get_travel_authority_region_counts()
RETURNS TABLE(region TEXT, total BIGINT)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    WITH normalized AS (
        SELECT
            id,
            lower(
                regexp_replace(
                    COALESCE(destination, ''),
                    '[^a-z0-9\s-]',
                    ' ',
                    'g'
                )
            ) AS destination_norm
        FROM public.travel_authorities
        WHERE is_demo = false
          AND COALESCE(destination, '') <> ''
    ),
    matched AS (
        SELECT
            n.id,
            a.region,
            ROW_NUMBER() OVER (
                PARTITION BY n.id
                ORDER BY a.priority DESC, char_length(a.alias) DESC
            ) AS rn
        FROM normalized n
        LEFT JOIN public.destination_region_aliases a
            ON position(a.alias IN n.destination_norm) > 0
    )
    SELECT
        COALESCE(region, 'Others') AS region,
        COUNT(*)::BIGINT AS total
    FROM matched
    WHERE rn = 1
    GROUP BY COALESCE(region, 'Others')
    ORDER BY total DESC, region;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_travel_authority_region_counts() TO authenticated;

COMMENT ON FUNCTION public.get_travel_authority_region_counts IS 'Returns region counts for dashboard insights by inferring region from the free-text destination field using a priority-based alias table.';
